### ISSUE TITLE
wrong link in "Forgot username or password"

### ISSUE THREAD

**Issue by mkudlej** [kmkanagaraj/usm-client-2#45]
When user click on $SUBJ links he can access into UI but without any data. I think after clicking on these links user should be redirected to page where he can renew his username and password. All supported user account types recovers should be available.

**Comment by kmkanagaraj** [comment]
@mkudlej  we don't have the support for this yet. We will be adding it.

**Comment by debloper** [comment]
Was working on this, but the current routing model makes it difficult to change the behavior without some key decision making.

In long term, we'll need a proper solution to this ([as explained in another issue](https://github.com/skyrings/kitoon/issues/93#issuecomment-157416619)), but for now if it helps to redirect users directly to `/dashboard` when clicked on those links - I can submit a patch for that.

N.B: I do realize that getting app interface for clicking on "Forgot username or password" is totally awkward. But if a proper solution takes time, I think giving users the dashboard view is better than a blank page (with dashboard link in the sidebar, another click away), for the time being.

**Comment by kmkanagaraj** [comment]
@debloper currently there is no support for resetting password in the backend. So we could remove the links for now and will add them back once the support is available.

**Comment by mkudlej** [comment]
I've filed BZ, please continue there https://bugzilla.redhat.com/show_bug.cgi?id=1298542 --> close issue
